app.constant('config', {
    apiUrl: 'http://35.154.8.228:8000/api/customer/',
    baseUrl: '/',
    enableDebug: true,
    domain: 'https://www.pixelsed.com/',
    jwplayerKey: 'pas6PhskOhNhbJ6Dz4UZXusRPUo0Ke9innm5hVm5yk8=',
    googleClientId: '448758546296-aquf7evhp5092d3acse4qc9ckkreqhs4.apps.googleusercontent.com',
    googleApiKey: 'AIzaSyDw76UlxuvVoIT2orwzEPLH_TRUISO5aaM',
    facebookSetAppId: '1816092075306094',
    facebookSetVersion: 'v2.8',
    facebookJSId: 'facebook-jssdk',
    facebookSdk: '//connect.facebook.net/en_US/sdk.js',
    loginType: 'WEBAPP',
    userType: ['STUDENT', 'TEACHER', 'AGENT', 'SUB_AGENT', 'SCHOOL'],
    gender: ['MALE', 'FEMALE', 'OTHERS'],
    socialType: ['FACEBOOK', 'GOOGLEPLUS'],
    accessRights: ['MANAGE_TOPICS', 'MANAGE_CUSTOMERS', 'SETTINGS'],
    packageType: ['AGENT_PACKAGE', 'ASSIGNED_PACKAGE', 'CLOSED_PACKAGE'],
    notificationType: ['REGISTRATION', 'PACKAGE_ADVERTISEMENT', 'COMPLETE_PROFILE', 'FREE_TOPIC_ADVERTISEMENT', 'ADD_CUSTOMER', 'PURCHASE_REQUEST'],
    message: {
        sentOtp: 'OTP sent successfully!!',
        userAdded: 'User added successfully.',
        selectTopics: 'Please select topics.',
        selectUsers: 'Please select users.',
        selectLanguage: 'Please select language.',
        selectCurriculum: 'Please select curriculum.',
        selectCategory: 'Please select category or content.',
        selectPackage: 'Please select packages.',
        completeYourProfile: 'Please complete your profile first.',
        mobileNumberAlreadyRegistered: 'Mobile number already registered with us. Please try another number.'
    }
});
